# Calamares master configuration for YukiOS
---
modules-search: [ /usr/lib/calamares/modules, local ]

instances:
- module:   welcome
  id:       welcome
  config:   welcome.conf

- module:   partition
  id:       partition
  config:   partition.conf

- module:   mount
  id:       mount
  config:   mount.conf

- module:   unpackfs
  id:       unpackfs
  config:   unpackfs.conf

- module:   machineid
  id:       machineid
  config:   machineid.conf

- module:   fstab
  id:       fstab
  config:   fstab.conf

- module:   locale
  id:       locale
  config:   locale.conf

- module:   localecfg
  id:       localecfg
  config:   localecfg.conf

- module:   hwclock
  id:       hwclock
  config:   hwclock.conf

- module:   keyboard
  id:       keyboard
  config:   keyboard.conf

- module:   packages
  id:       packages
  config:   packages.conf

- module:   users
  id:       users
  config:   users.conf

- module:   networkcfg
  id:       networkcfg
  config:   networkcfg.conf

- module:   displaymanager
  id:       displaymanager
  config:   displaymanager.conf

- module:   services-systemd
  id:       services-systemd
  config:   services-systemd.conf

- module:   shellprocess
  id:       shellprocess
  config:   shellprocess.conf

- module:   initcpiocfg
  id:       initcpiocfg
  config:   initcpiocfg.conf

- module:   initcpio
  id:       initcpio
  config:   initcpio.conf

- module:   grubcfg
  id:       grubcfg
  config:   grubcfg.conf

- module:   bootloader
  id:       bootloader
  config:   bootloader.conf

- module:   removeuser
  id:       removeuser
  config:   removeuser.conf

- module:   umount
  id:       umount
  config:   umount.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary

- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - localecfg
  - hwclock
  - keyboard
  - users
  - displaymanager
  - networkcfg
  - services-systemd
  - shellprocess
  - initcpiocfg
  - initcpio
  - grubcfg
  - bootloader
  - packages
  - removeuser
  - umount

- show:
  - finished

branding: yukios
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
