# Calamares bootloader configuration for YukiOS
---
efiBootLoader: "grub"

# systemd-boot
kernelSearchPath: "/usr/lib/modules"
kernelName: "vmlinuz"
timeout: "10"

bootloaderEntryName: "YukiOS"

# Grub
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true
