# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
displaymanagers:
  - sddm

defaultDesktopEnvironment:
  executable: "startplasma-wayland"
  desktopFile: "plasma"

basicSetup: false
sysconfigSetup: false
