# Calamares packages configuration for YukiOS
---
backend: pacman
skip_if_no_internet: true
update_db: false
update_system: false
pacman:
    num_retries: 0
    disable_download_timeout: false
    needed_only: false

operations:
  - try_remove:
    - calamares
    - ckbcomp
    - kpmcore
    - mkinitcpio-archiso
    - arch-install-scripts
