# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Shell process job for YukiOS target system cleanup before initcpio
---
dontChroot: false
timeout: 60
script:
    - "-/usr/local/bin/yukios-target-cleanup"
