# Calamares unpackfs configuration for YukiOS
---
unpack:
    - source: "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
      sourcefs: squashfs
      destination: "/"
      exclude:
        - "/etc/sudoers.d/*"
        - "/etc/mkinitcpio.conf.d/archiso.conf"
        - "/etc/mkinitcpio.d/linux.preset"
        - "/etc/systemd/system/getty@tty1.service.d/autologin.conf"
        - "/etc/sddm.conf.d/autologin.conf"
        - "/etc/lightdm*"
        - "/etc/systemd/system/pacman-init.service"
        - "/etc/systemd/system/choose-mirror.service"
        - "/etc/systemd/system/livecd-alsa-unmuter.service"
        - "/etc/systemd/system/livecd-talk.service"
        - "/etc/systemd/system/etc-pacman.d-gnupg.mount"
        - "/etc/systemd/journald.conf.d/volatile-storage.conf"
        - "/etc/systemd/resolved.conf.d/archiso.conf"
        - "/etc/systemd/logind.conf.d/do-not-suspend.conf"
        - "/etc/ssh/sshd_config.d/10-archiso.conf"
        - "/etc/xdg/autostart/calamares-autostart.desktop"
        - "/etc/xdg/autostart/trust-desktop.desktop"
      weight: 160

    - source: "/run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-linux-cachyos-lts"
      sourcefs: file
      destination: "/boot/vmlinuz-linux-cachyos-lts"
      weight: 5

    - source: "/run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-linux"
      sourcefs: file
      destination: "/boot/vmlinuz-linux"
      weight: 5
