# Calamares users configuration for YukiOS
---
defaultGroups:
    - lp
    - power
    - video
    - network
    - storage
    - wheel
    - audio
    - sys
    - optical
    - scanner
    - rfkill

autologinGroup:             autologin
doAutologin:                false
sudoersGroup:               wheel
setRootPassword:            true
doReusePassword:            false
allowWeakPasswords:         true
allowWeakPasswordsDefault:  false

userShell: /bin/bash
avatarFilePath: ~/.face
setHostname: EtcFile
writeHostsFile: true
