#
# /etc/pacman.conf for YukiOS
#

[options]
HoldPkg     = pacman glibc
Architecture = auto x86_64_v3

# Visual and performance enhancements
Color
ILoveCandy
ParallelDownloads = 5

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# Arch Linux Official Repositories
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# CachyOS Repositories
[cachyos-v3]
SigLevel = Optional TrustAll
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos-core-v3]
SigLevel = Optional TrustAll
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos-extra-v3]
SigLevel = Optional TrustAll
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos]
SigLevel = Optional TrustAll
Include = /etc/pacman.d/cachyos-mirrorlist

# BlackArch Repository
[blackarch]
SigLevel = Optional TrustAll
Include = /etc/pacman.d/blackarch-mirrorlist
